import { Scheme } from "@/types";

export const muxlaunchScheme: Scheme = ({ width }) => `[list]
LIST_DEFAULT_BACKGROUND_ALPHA = 0
LIST_DEFAULT_INDICATOR_ALPHA = 0
LIST_DEFAULT_TEXT_ALPHA = 0
LIST_DEFAULT_GLYPH_ALPHA = 0
LIST_DEFAULT_GLYPH_RECOLOUR_ALPHA = 0
LIST_DISABLED_TEXT_ALPHA = 0
LIST_FOCUS_BACKGROUND_ALPHA = 0
LIST_FOCUS_INDICATOR_ALPHA = 0
LIST_FOCUS_TEXT_ALPHA = 0
LIST_FOCUS_GLYPH_ALPHA = 0
LIST_FOCUS_GLYPH_RECOLOUR_ALPHA = 0

[misc]
ANIMATED_BACKGROUND = 0
CONTENT_PADDING_LEFT = 0
CONTENT_WIDTH = ${width}
NAVIGATION_TYPE = 0
STATIC_ALIGNMENT = 3
IMAGE_OVERLAY = 0
`;
